#!/usr/bin/env bash
#
# adb config script.

PATH="$PATH:/bin:/sbin:/usr/sbin"
androidHome=~/.android
androidConfig=~/.android/adb_usb.ini
custVID="0x2a70"

if [[ -e "$androidHome" ]]; then
    printf '%s\n' "Dir ~/.android already exists"
else
    printf '%s\n' "Dir ~/.android created"
    mkdir "$androidHome"
fi

grep "$custVID" "$androidConfig" 2>/dev/null

if [[ "$?" -eq 0 ]]; then
    printf '%s\n' "VID $custVID is already configured"
    printf '%s\n' "adb should be OK!"
    exit 0
else
    printf '%s\n' "Configuring adb..."
    printf '%s\n' "$custVID" >>"$androidConfig"
fi

adb kill-server

if [[ "$?" -eq 0 ]]; then
    printf '%s\n' "OK, now you can use adb"
    exit 0
else
    printf '%s\n' "Trying to execute adb with root permissions..."
    sudo adb kill-server

    if [ $? -eq 0 ] ; then
        printf '%s\n' "OK, now you can use adb"
        exit 0
    else
        printf '%s\n' "Please execute 'adb kill-server'"
    fi
fi

exit 0

