#!/usr/bin/env bash
#
# Generate a list of installed pkgs from official repos in Arch Linux.

 [[ "$1" == --dell ]] && fname="dell_arch_installed_pkgs"
 [[ "$1" == --asus ]] && fname="asus_arch_installed_pkgs"

# Create a file with the list of the installed pkgs from the official repos.
pacman -Qq > "$fname"

# Remove pkgs installed from the AUR.
for word in $(pacman -Qqm); do
  sed -i -e "s/^$word$//" \
         "$fname"
done

# Remove blank lines.
sed -i -e '/^\s*$/d' \
       "$fname"

# Calculate the number of installed pkgs.
n_pkgs="$(wc -l "$fname" | cut -d' ' -f1)"

# Print the number of installed pkgs.
printf '%s\n' "==> You have installed $n_pkgs packages from the official repos."
