#!/usr/bin/env bash
#
# Control ALSA controllers values.
# Uses FontAwesome icons for the current() function.

# Get the current volume value.
current() {
  nperc="$(amixer sget Master \
    | tail -n1 \
    | cut -d' ' -f6 \
    | cut -d[ -f2 \
    | cut -d] -f1)"

  vsta="$(amixer sget Master \
    | tail -n1 \
    | cut -d' ' -f8 \
    | cut -d[ -f2 \
    | cut -d] -f1)"

  case "$nperc" in
    [0-9])  iperc="\\uf026 ${nperc}%" ;;
    [1-3]?) iperc="\\uf026 ${nperc}%" ;;
    [4-6]?) iperc="\\uf027 ${nperc}%" ;;
    *)      iperc="\\uf028 ${nperc}%" ;;
  esac

  if [[ "$vsta" == off ]]; then
    if [[ "$iperc" =~ \ [0-9]%$ ]]; then
      iperc="$(printf '%b' "$iperc" | sed -e 's/[0-9]\+%/\.%/')"
    elif [[ "$iperc" =~ \ [0-9][0-9]%$ ]]; then
      iperc="$(printf '%b' "$iperc" | sed -e 's/[0-9]\+%/\.\.%/')"
    elif [[ "$iperc" =~ \ [0-9][0-9][0-9]%$ ]]; then
      iperc="$(printf '%b' "$iperc" | sed -e 's/[0-9]\+%/\.\.\.%/')"
    fi
  fi

  printf '%b\n' "$iperc"
}

[[ "$1" == --volup ]]   && amixer sset Master "$2"%+
[[ "$1" == --voldown ]] && amixer sset Master "$2"%-
[[ "$1" == --toggle ]]  && amixer sset Master toggle
[[ "$1" == --mute ]]    && amixer sset Master mute
[[ "$1" == --unmute ]]  && amixer sset Master unmute
[[ "$1" == --max ]]     && amixer sset Master 100%
[[ "$1" == --min ]]     && amixer sset Master 0%
[[ "$1" == --current ]] && current
