#!/usr/bin/env bash
#
# Create a create of KDE Plasma config files (.tar.gz archive).

tmpdir="$(mktemp -d)"

create()
{
  mkdir -p "${tmpdir}/bakde/k"
  mkdir -p "${tmpdir}/bakde/plasma"
  mkdir -p "${tmpdir}/bakde/kde4"

  cp -r ~/.config/k* "${tmpdir}/bakde/k"
  cp -r ~/.config/plasma* "${tmpdir}/bakde/plasma"
  cp -r ~/.kde4 "${tmpdir}/bakde/kde4"

  opwd="$PWD"
  cd "${tmpdir}" || exit 1
  tar -czf "${opwd}/bakde.tar.gz" ./bakde
  rm -rf "$tmpdir"
}

recover()
{
  cp "$1" "$tmpdir"
  tar xf "${tmpdir}/$1"
  mv "${tmpdir}/bakde" .
  rm -rf "$tmpdir"
}

main()
{
  [[ "$1" == --create ]]  && create
  [[ "$1" == --recover ]] && recover "$2"
}

main "$@"
