#!/usr/bin/env bash
#
# Create a backup of KDE Plasma config files (.tar.gz archive).

tmpdir="$(mktemp -d)"

backup()
{
  mkdir -p "${tmpdir}/bakde/k"
  mkdir -p "${tmpdir}/bakde/plasma"
  mkdir -p "${tmpdir}/bakde/kde4"

  cp -r ~/.config/k* "${tmpdir}/bakde/k"
  cp -r ~/.config/plasma* "${tmpdir}/bakde/plasma"
  cp -r ~/.kde4 "${tmpdir}/bakde/kde4"

  tar -czvf bakde.tar.gz "${tmpdir}/bakde"
  rm -rf "$tmpdir"
}

recover()
{
  cp "$1" "$tmpdir"
  tar xvf "${tmpdir}/$1"
  mv "${tmpdir}/bakde" .
  rm -rf "$tmpdir"
}

main()
{
  [[ "$1" == --backup ]]  && backup
  [[ "$1" == --recover ]] && recover "$2"
}
