#!/usr/bin/env bash

check-requirements-wrapper curl python

overwrite=false
[[ "$1" == -o ]] && overwrite=true

while IFS= read -r url; do
    file_name="$(printf '%s' "${url}" | fname-from-url)"
    [[ -f "${file_name}" && "${overwrite}" == false ]] && continue
    curl -Lo "${file_name}" -C- "${url}"
done < "${1:-/dev/stdin}"

