#!/usr/bin/env bash

slap deps dunstify || exit 1

FULL_AT=87

now="$(</sys/class/power_supply/BAT0/energy_now)"
full="$(</sys/class/power_supply/BAT0/energy_full)"
percentage="$((now * 100 / full))"
relative_percentage="$((percentage * 100 / FULL_AT))"

dunstify Battery "${relative_percentage}%"

