#!/usr/bin/env bash
#
# Create a directory hierarchy that I use to save the album covers.

idir="${HOME}/immagini/album-covers"

for i in *; do
  # Do these operations only if it is a file, not a directory.
  if [[ -f "$i" ]]; then
    artist="$(printf '%s' "$i" \
             | cut -d- -f1 \
             | sed "s/'/\\\'/g" \
             | xargs)"
    title="$(printf '%s' "$i" \
            | cut -d- -f2- \
            | sed "s/'/\\\'/g" \
            | sed 's/.mp3//' \
            | xargs)"

    mkdir -p "${idir}/${artist}/${i/.mp3}"
  fi
done
