#!/usr/bin/env bash
#
# Clear aurman cache.

garbage_size="$(du -h "${HOME}/.cache/aurman" \
               | tail -n1 \
               | awk '{ print $1 }')"

for garbage in ~/.cache/aurman/*; do
  [[ -d "$garbage" ]] && \
    rm -rf "$garbage"
done

printf '%s\n' "You have cleaned $garbage_size of aurman cache."
