#!/usr/bin/env bash
#
# Script tattico per aiutare il MuBerad.

printf '%s\n' "wal -c -q --backend wal -i ~/progetti/wallpapers -o ~/bin/wal-set" >> "${HOME}/.config/openbox/autostart"

printf '%s\n' "Masiero Matte, ora dovrebbe andare ad ogni avvio senza il bisogno che tu prema W-c o A-c."
              "Tra qualche secondo il computer si riavvierà da solo per testare."

sleep 10
reboot
