#!/usr/bin/env bash

slap deps shellcheck fd rg || exit 1

# shellcheck disable=SC2016,SC2046
shellcheck --enable=all $(fd --exclude .git -tx -H -X head -1 \
    | rg '==> ([^ ]+) <==\n.+(?:bash|sh|dash|ksh)$' -r '$1' -oUa)
