#!/usr/bin/env bash

successful=true

for not_installed_program in $(check-requirements "$@"); do
    successful=false
    printf "%s\n" "'${not_installed_program}' is required but not installed"
done

[[ "${successful}" == false ]] && exit 1 || exit 0

