#!/usr/bin/env bash
#
# Small utility to convert decimal numbers to octal.

check_if_null() {
  if [[ "$(printf '%s' "$partial" | cut -d. -f2)" =~ [1-9] ]]; then
    checkres="nonzero"
  fi
}

calc_reminder() {
  reminder="$(( dividend_bak - "$(( dividend * 8 ))" ))"

  reminder_total+="$reminder"
}

ndec="$1"
dividend="$ndec"

while true; do
  if [[ "$dividend" -ne 0 ]]; then
    dividend_bak="$dividend"
    partial="$(bc -l <<<"$dividend / 8" )"
    dividend="$(printf '%s' "$partial" | cut -d. -f1)"
    [[ -z "$dividend" ]] && dividend=0

    check_if_null
    if [[ "$checkres" == nonzero ]]; then
      calc_reminder
    else
      reminder_total+=0
    fi
  else
    break
  fi
done


printf '%s\n' "$(printf '%s' "$reminder_total" | rev)"
