#!/usr/bin/env bash

slap deps dunstify || exit 1

active_desktops=""
for i in $(seq 0 8); do
    lines_no="$(xdotool search --desktop "${i}" '.*' 2>/dev/null | wc -l)"
    [[ "${lines_no}" -gt 0 ]] && active_desktops+="$((i + 1)) "
done
dunstify "Active desktops" "${active_desktops}" -r 3

