#!/usr/bin/env bash
#
# A script that sets eighties as my terminal colorscheme.

# Change the terminal colors to source.
sed -i -e 's/! Include .*/! Include eighties colors\./' \
       -e 's_#include .*_#include "/home/matte/progetti/themes/xresources/base16-eighties.Xresources"_' \
       "${HOME}/.Xresources"

# Reload .Xresources.
xrdb "${HOME}/.Xresources"

# Execute a hook script.
"${HOME}/bin/base16-set"

# Change the rofi theme to source.
sed -i -e 's_rofi.theme: .*_rofi.theme:             progetti/themes/rofi/colors-rofi.rasi_' \
       "${HOME}/.Xresources"

# Switch to "base16 mode".
sed -i -e 's/^!if 1/if 1/' \
       -e 's/^!if 0/if 0/' \
       -e 's/^if 0/!if 0/' \
       "${HOME}/.config/nvim/init.vim"

# Reload everything.
xrdb "${HOME}/.Xresources"
for pid in $(pidof xst); do kill -s USR1 "$pid"; done
