#!/usr/bin/env bash

while IFS= read -r line; do
    if [[ "$(isurl <<<"${line}")" == true ]]; then
        fname="$(fname-from-url <<<"${line}")"
    else
        fname="${line}"
    fi

    printf '%s\n' "$(rev <<<"${fname}" | cut -d. -f1 | rev)"
done < "${1:-/dev/stdin}"

