#!/usr/bin/env bash
#
# A script that exploits the "$RANDOM" variable that bash generates to set a casual wallpaper from a folder containing multiple wallpapers.

# Change this to your wallpaper folder.
wal_folder="${HOME}/progetti/wallpapers"

# Previous wallpaper.
wal_pre="$(printf '%s\n' "$(<"${HOME}/.fehbg")" | tail -n1 | awk '{ print $3 }' | sed "s/'//g")"

# Save the random integer for later.
RANDINT="$RANDOM"

c=0
while [[ "$c" -le "$RANDINT" ]]; do
  for wallpaper in "$wal_folder"/*; do
    ((c++))
    if [[ "$c" -eq "$RANDINT" ]]; then
      if [[ "$wallpaper" == "$wal_pre" ]]; then
        RANDINT="$RANDOM"
        c=0
      else
        feh --bg-fill "$wallpaper"
      fi
    fi
  done
done
