#!/usr/bin/env fish
#
# A script that I don't use anymore but it's still too interesting to just
# delete it.
# Basically it sends to all active pseudo terminals an escape sequence that
# change the value of color17.
# I primarily needed this trick for my wal.vim fork.
# Works with FISH shell.

if test -f "$HOME/.cache/wal/colors.fish"
  . "$HOME/.cache/wal/colors.fish"
  if test (cat "$HOME/.cache/wal/mode") = "dark"
    set c0l150_1 (printf "$color0_lighter_150" | cut -c2-3)
    set c0l150_2 (printf "$color0_lighter_150" | cut -c4-5)
    set c0l150_3 (printf "$color0_lighter_150" | cut -c6-7)
    printf '%b' "\\e]4;17;rgb:$c0l150_1/$c0l150_2/$c0l150_3\\e\\" >/dev/tty
  else if test (cat "$HOME/.cache/wal/mode") = "light"
    set c0d20_1 (printf "$color0_darker_20"   | cut -c2-3)
    set c0d20_2 (printf "$color0_darker_20"   | cut -c4-5)
    set c0d20_3 (printf "$color0_darker_20"   | cut -c6-7)
    printf '%b' "\\e]4;17;rgb:$c0d20_1/$c0d20_2/$c0d20_3\\e\\" >/dev/tty
  end
end
