#!/usr/bin/env bash
#
# Download and install plug.vim

# Download plug.vim and put it in the right place.
curl -fsSLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
