#!/usr/bin/env bash
#
# Install the Wi-Fi driver for my old DELL laptop.

# Create a temporary folder to save the firmware.
fwtmpdir="$(mktemp -d)"

# Download the firmware.
wget -O http://www.lwfinger.com/b43-firmware/broadcom-wl-5.100.138.tar.bz2 \
        "${fwtmpdir}/broadcom-wl-5.100.138.tar.bz2"
tar xvjf "${fwtmpdir}/broadcom-wl-5.100.138.tar.bz2"

# Install the extractor and extract the firmware.
sudo xbps-install -Syv b43-fwcutter
b43-fwcutter -w /usr/lib/firmware \
                "${tmpdir}/broadcom-wl-5.100.138/linux/wl_apsta.o"

# Remove the temp dir.
rm -rf "$fwtmpdir"
