#!/usr/bin/env bash
#
# Small script for converting hexadecimal numbers to decimal using bc.

[[ "$1" =~ [g-z] || "$1" =~ [G-Z] ]] && \
  printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37mImpara a scrivere e ritenta, sarai più fortunato.\\e[0m" && \
  exit 1

n="$(printf '%s\n' "$1" \
    | sed -e 's/a/A/g' \
          -e 's/b/B/g' \
          -e 's/c/C/g' \
          -e 's/d/D/g' \
          -e 's/e/E/g' \
          -e 's/f/F/g')"

bc <<<"ibase=16; $n"
