#!/usr/bin/env bash
#
# Small script for converting hexadecimal numbers to decimal using bc.

[[ "$1" =~ [g-z] || "$1" =~ [G-Z] ]] && \
  printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37mImpara a scrivere e ritenta, sarai più fortunato.\\e[0m"

bc <<<"ibase=16; obase=10; $1"
