#!/usr/bin/env bash
#
# Connect to my smartphone's hotspot.

sudo -p "$(tput bold)$(tput setaf 1)~~> $(tput sgr0)" netctl stop casa
sudo -p "$(tput bold)$(tput setaf 1)~~> $(tput sgr0)" netctl start hotspot
