#!/usr/bin/env bash

slap deps curl sxiv || exit 1

file_paths=()

while IFS= read -r line; do
    line_is_url="$(printf '%s\n' "${line}" | isurl)"
    if [[ "${line_is_url}" == true ]]; then
        file_path="$(mktemp)"
        curl -Lo "${file_path}" -C- "${line}"
        file_paths+=("${file_path}")
    else
        file_paths+=("${line}")
    fi
done < "${1:-/dev/stdin}"

sxiv "${file_paths[@]}"

