#!/usr/bin/env bash
#
# Returns exit code 0 if the chosen Workspace is current, returns 1 otherwise.

currentws="$(wmctrl -d | rg '\*' | awk '{print $1}')"

if [[ "$1" == "$currentws" ]]; then
  exit 0
else
  exit 1
fi
