#!/usr/bin/env bash

while IFS= read -r line; do
    printf '%s' "$line" | \
        rg 'https?://(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)' >/dev/null 2>&1 \
        && echo true \
        || echo false
done < ${1:-/dev/stdin}

