#!/usr/bin/env bash

for repo in "${HOME}/progetti/"*; do
    cd "${repo}" || exit 1
    [[ -n "$(git status --porcelain --ignore-submodules)" ]] && {
        printf '%s\n' "${repo}"
    }
    cd .. || exit 1
done

