#!/usr/bin/env bash
#
# Simple screen locker.
# Requires imagemagick.

# Remove old screenshots.
mkdir -p "${HOME}/.cache/locker"
rm -f "${HOME}/.cache/locker/scr{,-blurred}.png"

# Take a non-blurred screenshot.
import -window root "${HOME}/.cache/locker/scr.png"

# Blur the screenshot.
convert "${HOME}/.cache/locker/scr.png" \
  -filter Gaussian \
  -blur 0x8 \
  "${HOME}/.cache/locker/scr-blurred.png"

# Lock the screen with the blurred screenshot.
i3lock -u -i "${HOME}/.cache/locker/scr-blurred.png"
