#!/usr/bin/env bash

check-requirements-wrapper ffmpeg rev cut

ffmpeg -n \
    -protocol_whitelist file,http,https,tcp,tls,crypto \
    -i "$1" \
    -c copy \
    -bsf:a aac_adtstoasc \
    "$(rev <<<"$2" | cut -d. -f2- | rev).mp4"

