#!/usr/bin/env bash
#
# A script that sets material-darker as my terminal colorscheme.

# Change the terminal colors to source.
sed -i -e 's/! Include .*/! Include material-darker colors\./' \
       -e 's_#include .*_#include "/home/matte/progetti/themes/xresources/material-darker.Xresources"_' \
       "${HOME}/.Xresources"

# Reload .Xresources.
xrdb "${HOME}/.Xresources"

# Execute a hook script.
"${HOME}/bin/theme-set"

# Change the rofi theme to source.
sed -i -e 's_rofi.theme: .*_rofi.theme:             progetti/themes/rofi/colors-rofi.rasi_' \
       "${HOME}/.Xresources"

# Reload everything.
xrdb "${HOME}/.Xresources"
for pid in $(pidof xst); do kill -s USR1 "$pid"; done
