#!/usr/bin/env bash
#
# Utile per scuola.

# Approssima a tre cifre significative.
approssima() {
  votapprox=false
  medapprox=false

  if [[ -z "$(printf '%s' "$media" | cut -d. -f1)" ]]; then
    media=0."$(printf '%s' "$media" \
              | cut -d. -f2)"
  elif [[ -z "$(printf '%s' "$voto_per_suff" | cut -d. -f1)" ]]; then
    voto_per_suff=0."$(printf '%s' "$voto_per_suff" \
                      | cut -d. -f2)"
  fi

  if [[ "$(printf '%s' "$media" | cut -d. -f2)" -eq 0 ]]; then
    media="$(printf '%s' "$media" \
            | cut -d. -f1)"
    medapprox=true
  fi
  if [[ "$(printf '%s' "$voto_per_suff" | cut -d. -f2)" -eq 0 ]]; then
    voto_per_suff="$(printf '%s' "$media" \
                    | cut -d. -f1)"
    votapprox=true
  fi

  if [[ "$(printf '%s' "$media" | cut -d. -f2 | cut -c2-2)" -eq 0 && "$medapprox" == false ]]; then
    media="$(printf '%s' "$media" \
            | cut -d. -f1).$(printf '%s' "$media" \
            | cut -d. -f2 \
            | cut -c1-1)"
  elif [[ "$(printf '%s' "$media" | cut -d. -f2 | cut -c3-3)" -eq 0 && "$medapprox" == false ]]; then
    media="$(printf '%s' "$media" \
            | cut -d. -f1).$(printf '%s' "$media" \
            | cut -d. -f2 \
            | cut -c1-2)"
  elif [[ "$(printf '%s' "$media" | cut -d. -f2 | cut -c4-4)" -ge 5 && "$medapprox" == false ]]; then
    media="$(printf '%s' "$media" \
            | cut -d. -f1).$(printf '%s' "$media" \
            | cut -d. -f2 \
            | cut -c1-2)$(( "$(printf '%s' "$media" \
            | cut -d. -f2 \
            | cut -c3-3)" + 1 ))"
  elif [[ "$medapprox" == false ]]; then
    media="$(printf '%s' "$media" \
            | cut -d. -f1).$(printf '%s' "$media" \
            | cut -d. -f2 \
            | cut -c1-2)$(( "$(printf '%s' "$media" \
            | cut -d. -f2 \
            | cut -c3-3)" - 1 ))"
  fi

  if [[ "$(printf '%s' "$voto_per_suff" | cut -d. -f2 | cut -c2-2)" -eq 0 || "$votapprox" == false ]]; then
    voto_per_suff="$(printf '%s' "$voto_per_suff" \
                    | cut -d. -f1).$(printf '%s' "$voto_per_suff" \
                    | cut -d. -f2 \
                    | cut -c1-1)"
  elif [[ "$(printf '%s' "$voto_per_suff" | cut -d. -f2 | cut -c3-3)" -eq 0 || "$votapprox" == false ]]; then
    voto_per_suff="$(printf '%s' "$voto_per_suff" \
                    | cut -d. -f1).$(printf '%s' "$voto_per_suff" \
                    | cut -d. -f2 \
                    | cut -c1-2)"
  elif [[ "$(printf '%s' "$voto_per_suff" | cut -d. -f2 | cut -c4-4)" -ge 5 || "$votapprox" == false ]]; then
    voto_per_suff="$(printf '%s' "$voto_per_suff" \
                    | cut -d. -f1).$(printf '%s' "$voto_per_suff" \
                    | cut -d. -f2 \
                    | cut -c1-2)$(( "$(printf '%s' "$voto_per_suff" \
                    | cut -d. -f2 \
                    | cut -c3-3)" + 1 ))"
  elif [[ "$votapprox" == false ]]; then
    voto_per_suff="$(printf '%s' "$voto_per_suff" \
                    | cut -d. -f1).$(printf '%s' "$voto_per_suff" \
                    | cut -d. -f2 \
                    | cut -c1-2)$(( "$(printf '%s' "$voto_per_suff" \
                    | cut -d. -f2 \
                    | cut -c3-3)" - 1 ))"
  fi
}

# Conta i voti.
# shellcheck disable=SC2034
for i in $1; do
  ((nvoti++))
done

# Calcola la media aritmetica dei voti.
voti_sommati="$(bc -l <<<"$(printf '%s' "$1" \
               | sed 's/ /+/g')")"
media="$(bc -l <<<"$voti_sommati / $nvoti")"

# Calcola il voto per il quale la media aritmetica dei voti sarebbe uguale a 6.
#
#  voti_sommati + voto_per_suff
#  ----------------------------  =  6
#           nvoti + 1
#
#  voto_per_suff  =  6 ∙ (nvoti + 1) - voti_sommati
#
voto_per_suff="$(bc -l <<<"6 * ($nvoti + 1) - $voti_sommati")"

# Se il voto per la sufficienza è maggire di 10, è inutile perchè è oltre i
# limiti del sistema di valutazione scolastico.
# L'equazione si complica un po' ma almeno il voto per la sufficienza è sempre
# <= 10.
#
#  voti_sommati + c ∙ voto_per_suff
#  --------------------------------  =  6
#              nvoti + c
#
#                  6 ∙ (nvoti + c) - voti_sommati
#  voto_per_suff = ------------------------------
#                                c
#
c=1
while [[ "$(bc -l <<<"$voto_per_suff > 10")" -eq 1 ]]; do
  ((c++))
  voto_per_suff="$(bc -l <<<"(6 * ($nvoti + $c) - $voti_sommati) / $c")"
done

# Dai in output la media.
if [[ "$(bc -l <<<"$media < 6")" -eq 1 ]]; then
  approssima
  printf '%b\n' "\\e[1;31m:: \\e[1;37mLa tua media è di $media."

  if [[ "$c" -eq 1 ]]; then
    printf '%b\n' "   Devi prendere almeno $voto_per_suff.\\e[0m"
  elif [[ "$c" -ne 1 ]]; then
    printf '%b\n' "   Devi prendere $voto_per_suff per almeno $c volte.\\e[0m"
  fi
elif [[ "$(bc -l <<<"$media > 6")" -eq 1 ]]; then
  approssima
  printf '%b\n' "\\e[1;31m:: \\e[1;37mLa tua media è di $media."

  if [[ "$c" -eq 1 ]]; then
    printf '%b\n' "   Attento a non prendere meno di $voto_per_suff.\\e[0m"
  elif [[ "$c" -ne 1 ]]; then
    printf '%b\n' "   Attento a non prendere meno di $voto_per_suff per almeno $c volte.\\e[0m"
  fi
fi
