#!/usr/bin/env bash
#
# A script for creating a .NET Core Console application template with dotnet
# command.

Nuovo()
{
  dotnet new console
  dotnet build
  csc Program.cs
  chmod +x Program.exe
}

Esistente()
{
  mv "$1" "$1.bak"
  dotnet new console
  dotnet build
  rm Program.cs
  mv "$1.bak" "$1"
  csc "$1"
  chmod +x Program.exe
}

Main()
{
  [[ -z "$1" ]] && Nuovo
  [[ "$1" ]]    && Esistente "$1"
}

Main "$@"
