#!/usr/bin/env bash
#
# Generate pdfs from markdown files using pandoc.

for text in *; do
  [[ -d "$text" ]] && continue

  if [[ "${text##*.}" == md || "${text##*.}" == txt || ! "$text" =~ \. ]]; then
    formatta() {
      if [[ "${text##*.}" == md ]]; then
        tpdf="${text/.md/.pdf}"
      elif [[ "${text##*.}" == txt ]]; then
        tpdf="${text/.txt/.pdf}"
      else
        tpdf="${text}.pdf"
      fi
    }

    formatta

    if [[ "$1" == --no-sminchiato ]]; then
      pandoc -V lang=it -f markdown-implicit_figures -o "$tpdf" "$text"
    elif [[ "$1" == --no-sminchiato-toc ]]; then
      pandoc -V lang=it -s --toc -f markdown-implicit_figures -o "$tpdf" "$text"
    elif [[ "$1" == --toc ]]; then
      pandoc -V lang=it -s --toc -o "$tpdf" "$text"
    else
      pandoc -V lang=it -o "$tpdf" "$text"
    fi
  fi
done
