#!/usr/bin/env bash
#
# Extract artist name and song title from the file name and based on that, add
# correct id3v2 tags to the song.
# I use this version of the script in other devices than my Arch Linux system.

for i in *; do
  # Do these operations only if it is a file, not a directory.
  #shellcheck disable=SC1117
  if [[ -f "$i" ]]; then
    artist="$(printf '%s' "$i" \
             | cut -d- -f1 \
             | sed "s/'/\\\'/g" \
             | xargs)"
    title="$(printf '%s' "$i" \
            | cut -d- -f2- \
            | sed "s/'/\\\'/g" \
            | sed 's/.mp3//' \
            | xargs)"

    id3v2 --delete-all "$i"
    id3v2 --artist "$artist" \
          --song "$title" \
          "$i"
  fi
done
