#!/usr/bin/env bash
#
# Small utility to convert octal numbers to decimal.

noct="$1"
noct_len="$(printf '%s' "$noct" | wc -m)"
c="$noct_len"
p=0

while [[ "$c" -gt 0 ]]; do
  partial_dec="$(( "$(printf '%s' "$noct" | cut -c"$c"-"$c")" * 8 ** "$p" ))"
  dec="$((dec + partial_dec))"
  ((c--))
  ((p++))
done

printf '%s\n' "$dec"
