#!/usr/bin/env/bash
#
# Small script for converting octal numbers to binary using bc.

[[ "$1" =~ [8-9] || "$1" =~ [a-z] || "$1" =~ [A-Z] ]] && \
  printf '%b\n' "\\e[1;31m::\\e[0m \\e[1;37mImpara a scrivere e ritenta, sarai più fortunato.\\e[0m"

bc <<<"ibase=2; obase=10; $1"
