#!/usr/bin/env bash
#
# A script that I don't use anymore but it's still too interesting to just
# delete it.
# Basically it sends to all active pseudo terminals an escape sequence that
# change the value of color17.
# I primarily needed this trick for my wal.vim fork.
# Works for bash and other POSIX compliant shells like zsh.

if [[ -f "${HOME}/.cache/wal/colors.sh" ]]; then
  . "${HOME}/.cache/wal/colors.sh"
  if [[ "$(<"${HOME}/.cache/wal/mode")" == dark ]]; then
    printf '%b' "\\e]4;17;rgb:${color0_lighter_150:1:2}/${color0_lighter_150:3:2}/${color0_lighter_150:5:2}\\e\\"
  elif [[ "$(<"${HOME}/.cache/wal/mode")" == light ]]; then
    printf '%b' "\\e]4;17;rgb:${color0_darker_20:1:2}/${color0_darker_20:3:2}/${color0_darker_20:5:2}\\e\\"
  fi
fi
