#!/usr/bin/env bash

choice="$(printf '%s\n%s\n%s\n%s\n%s' "suspend" "reboot" "shutdown" "exit xorg" "nothing" \
    | rofi -dmenu)"

case "${choice}" in
    suspend)
        systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    "exit xorg")
        killall Xorg
        ;;
    *)
        exit
        ;;
esac

