#!/usr/bin/env bash
#
# Count how many files/folders there are in the current directory.

# cd into the directory if it exists, if it does not exist display an error mex.
if [[ "$1" ]]; then
  if [[ -d "$1" ]]; then
    cd "$1" || exit 1
  elif [[ ! -d "$1" ]]; then
    printf '%b\n' "\\e[1;31m:: Dir doesn't exist.\\e[0m"
    exit 1
  fi
fi

# Display the count of files/folders.
if [[ -z "$(ls)" ]]; then
  printf '%b\n' "\\e[1;31m:: There are no files/folders.\\e[0m"
else
  #shellcheck disable=2034
  for i in *; do
    ((c += 1))
  done
  printf '%b\n' "\\e[1;31m:: \\e[1;37mThere are $c files/folders.\\e[0m"
fi
