#!/usr/bin/env bash
#
# A small script for generating random numbers that are between a min and max number.

# Parameter parsing.
if [[ "$1" == --min && "$3" == --max ]]; then
  nmin="$2"
  nmax="$4"
elif [[ "$1" == --max && "$3" == --min ]]; then
  nmax="$2"
  nmin="$4"
else
  printf '%b\n' "\\e[1;31m:: Specifiy the minimum number with the --min parameter and the maximum with the --max parameter.\\e[0m"
  exit 1
fi

randint="$RANDOM"

# Create an array from $nmin to $nmax.
rand_array="$nmin"
for ((item="$((nmin+1))"; item<="$nmax"; item++)); do
  rand_array+=" $item"
done

# Output a random integer in the range of $rand_array.
c=0
while true; do
  [[ "$varexit" == true ]] && break

  for i in $rand_array; do
    if [[ "$c" -eq "$randint" ]]; then
      randout="$i"
      varexit=true
      break
    fi

    ((c++))
  done
done

# Output the random integer.
printf '%s\n' "$randout"
