#!/usr/bin/env python3

"""
Usage: ratio "x : 75 = 60 : 100"
Spaces are necessary
"""

import sys

args = list(filter(lambda x: x != ":" and x != "=", sys.argv[1].split(" ")))

first, second, third = [
    (1, 2, 3),
    (0, 3, 2),
    (0, 3, 1),
    (1, 2, 0),
][args.index("x")]

print(str(int(args[first]) * int(args[second]) / int(args[third])))

