#!/usr/bin/env bash

trim_string() {
    : "${1#"${1%%[![:space:]]*}"}"
    : "${_%"${_##*[![:space:]]}"}"
    printf '%s\n' "$_"
}

remove_trailing_colon() {
    [[ "${1: -1}" == ':' ]] && printf '%s\n' "${1::-1}" || printf '%s\n' "$1"
}

: "$(trim_string "$1")"
: "$(remove_trailing_colon "$_")"
rofi -dmenu -p "$_"

