#!/usr/bin/env bash

check-requirements-wrapper rofi

trim_string() {
    : "${1#"${1%%[![:space:]]*}"}"
    : "${_%"${_##*[![:space:]]}"}"
    printf '%s\n' "${_}"
}

remove_trailing_colon() {
    if [[ "${1: -1}" == ':' ]]; then
        printf '%s\n' "${1::-1}"
    else
        printf '%s\n' "$1"
    fi
}

: "$(trim_string "$1")"
: "$(remove_trailing_colon "${_}")"
rofi -dmenu -p "${_}"

