#!/usr/bin/env bash
#
# stow sometimes is buggy...

tmp_dir="$(mktemp -d)"

cp "${HOME}/.config/fish/config.fish" "$tmp_dir"
cp "${HOME}/.Xresources"              "$tmp_dir"

rm -f "${HOME}/.config/fish/config.fish" \
      "${HOME}/.Xresources" \
      "${HOME}/progetti/dotfiles/dotfiles/fish/.config/fish/config.fish" \
      "${HOME}/progetti/dotfiles/dotfiles/x/.Xresources"

cp "${tmp_dir}/config.fish" "${HOME}/progetti/dotfiles/dotfiles/fish/.config/fish"
cp "${tmp_dir}/.Xresources" "${HOME}/progetti/dotfiles/dotfiles/x"

cd "${HOME}/progetti/dotfiles/dotfiles" || exit 1
stow -t "${HOME}" x fish

rm -rf "$tmp_dir"
