#!/usr/bin/env bash
#
# A simple script to take screenshots while hiding the terminal cursor.
# Originally written by Dylan Araps.

# Source pywal colors.
. "${HOME}/.cache/wal/colors.sh"

# Store the time as variable.
printf -v time "%(%H:%M:%S)T" "-1"

# Where the screenshot is saved.
scr_dir="${HOME}/immagini"

# Name of the screenshot.
scr="${scr_dir}/${time}"

# Send a set of characters to all open terminals.
send_to_terms() {
  for term in /dev/pts/[0-9]*; do
    [[ -w "$term" ]] && printf "%b" "$1" > "$term" &
  done
}

# Hide terminal cursors when taking a scrot.
send_to_terms "\\e[?25l"
import -window root "$scr".png &
sleep 2
send_to_terms "\\e[?25h"

# Open the screenshot in pqiv.
pqiv -i --box-colors="$color7":"$color0_lighter_90" --bind-key="@MONTAGE { h { montage_mode_shift_x(-1) } }" --bind-key="@MONTAGE { j { montage_mode_shift_y(1) } }" --bind-key "@MONTAGE { k { montage_mode_shift_y(-1) } }" --bind-key "@MONTAGE { l { montage_mode_shift_x(1) } }" --bind-key="j { goto_file_relative(-1) }" --bind-key="k { goto_file_relative(1) }" --bind-key="h { goto_file_relative(-1) }" --bind-key="l { goto_file_relative(1) }" --bind-key="d { command(rm $1) }" "$scr".png
