#!/usr/bin/env bash

slap deps git basename || exit 1

repos_path="${1:-/home/matte/progetti}"
github_username="${2:-agnipau}"

for repo in "${repos_path}/"*; do
    [[ -d "${repo}" ]] && {
        (
            cd -- "${repo}/" || exit 1
            git remote set-url origin \
                "git@github.com:${github_username}/$(basename "${repo}").git"
        )
    }
done

