#!/usr/bin/env python3

import os
import sys


def main():
    args = sys.argv[1:]
    if len(args) != 1:
        print('Usage: python3 sloc.py /path/to/dir')
        exit(1)
    path = args[0]

    sloc = 0
    for root, _, files in os.walk(path):
        for f in files:
            sloc += sum(1 for _ in open(os.path.join(root, f)))
    print(sloc)


if __name__ == '__main__':
    main()
