#!/bin/env bash
# Copyright 2017-2018 by SDRausty. All rights reserved.  🌎 🌍 🌏 🌐 🗺 
# Hosting sdrausty.github.io/TermuxArch courtesy https://pages.github.com.
# https://sdrausty.github.io/TermuxArch/README has info about this project.
# https://sdrausty.github.io/TermuxArch/CONTRIBUTORS Thank you for your help.
################################################################################
# IFS=$'\n\t'
set -Eeuo pipefail
# shopt -s nullglob globstar
unset LD_PRELOAD
VERSIONID=v1.6.7.id5677
 
_TRPERR_() {  #	Run on script error.
	local RV="$?"
	printf "\e[?25h\n\e[1;48;5;138m %s\e[0m\n\n" "TermuxArch WARNING:  Generated script signal ${RV:-unknown} near or at line number ${1:-unknown} by `${2:-command}`!"
	exit 201
}
 
_TRPET_() {  #	Run on exit.
	local RV="$?" 
  	printf "\a\a\a\a" 
	sleep 0.4 
	if [[ "$RV" = 0 ]] ; then
		printf "\a\e[0;32m%s\e[1;34m: \a\e[1;32m%s\e[0m\n\n\a\e[0m" "${0##*/} $@ v1.6.7.id5677" "DONE 🏁 "
		printf "\e]2; %s: %s \007" "${0##*/} $@" "DONE 🏁 "
	else 
		printf "\a\e[0;32m%s \a\e[0m%s\e[1;34m: \a\e[1;32m%s\e[0m\n\n\a\e[0m" "${0##*/} $@ v1.6.7.id5677" "[Exit Signal $RV]" "DONE  🏁 "
		printf "\033]2; %s: %s %s \007" "${0##*/} $@" "[Exit Signal $RV]" "DONE 🏁 "
	fi
	printf "\e[?25h\e[0m"
	set +Eeuo pipefail
	exit
}
 
_TRPSIG_() {  #	Run on signal.
	printf "\e[?25h\e[1;7;38;5;0mTermuxArch WARNING:  Signal $? received!\e[0m\n"
 	exit 211
}
 
_TRPQ_() {  #	Run on quit.
	printf "\e[?25h\e[1;7;38;5;0mTermuxArch WARNING:  Quit signal $? received!\e[0m\n"
 	exit 221
}
 
trap "_TRPERR_ $LINENO $BASH_COMMAND $?" ERR
trap _TRPET_ EXIT
trap _TRPSIG_ HUP INT TERM
trap _TRPQ_ QUIT
 
## BEGIN #######################################################################

COMMANDIF="$(command -v getprop)" ||:
if [[ "$COMMANDIF" = "" ]] ; then
 		printf "\n\e[1;48;5;138m  %s\e[0m\n\n" "${0##*/} WARNING: Run ${0##*/} and /data/data/com.termux/files/home/arch/${0##*/} from the BASH shell in the OS system in Termux, e.g., Amazon Fire, Android and Chromebook."
exit 202
fi
declare -g ar2ar="${@:2}"
declare -g ar3ar="${@:3}"
_PRINTUSAGE_() { 
printf "\e]2;%s\007" "TermuxArch startarch help 📲" 
printf "\n\e[1;32m%s\e[0;32m%s\n\n" "startarch" ": Start Arch Linux as root.  This account is reserved for system administration."  
printf "\e[1;32m%s\e[0;32m%s\n\n" "startarch c[md] cmd" ": Run Arch Linux command from Termux as root user." 
printf "\e[1;32m%s\e[0;32m%s\e[1;32m%s\e[0;32m%s\n\n" "startarch u[ser]|l[ogin] user" ": Login as user.  Use " "startarch c addauser user " "first to create this user and user's home directory."
printf "\e[1;32m%s\e[0;32m%s\e[1;32m%s\e[0;32m%s\e[1;32m%s\e[0;32m%s\n\n" "startarch r[aw]" ": Construct the " "startarch " "proot statement from exec.../bin/.  For example " "startarch r su " "will exec su in Arch Linux."
printf "\e[1;32m%s\e[0;32m%s\e[1;32m%s\e[0;32m%s\n\n\e[0m" "startarch s[u] user cmd" ": Login as user and execute command.  Use " "startarch c addauser user " "first to create this user and user's home directory."
}

# [] Default Arch Linux in Termux PRoot root login.
if [[ -z "${1:-}" ]];then
set +Eeuo pipefail
exec proot --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch -b /data/data/com.termux/files/home/arch/tmp:/dev/shm -b /data/data/com.termux/files/home/arch/var/binds/fbindprocstat:/proc/stat -b /proc/self/fd/1:/dev/stdout -b /proc/self/fd/2:/dev/stderr -b "$ANDROID_DATA" -b /dev/ -b "$EXTERNAL_STORAGE" -b "$HOME" -b /proc/ -b /storage/ -b /sys/ -w "$PWD" /usr/bin/env -i HOME=/root TERM=xterm-256color  /bin/bash -l ||: 
set -Eeuo pipefail
printf '\033]2; TermuxArch startarch 📲  \007'
# [?|help] Displays usage information.
elif [[ "${1//-}" = [?]* ]] || [[ "${1//-}" = [Hh]* ]] ; then
_PRINTUSAGE_
# [command ARGS] Execute a command in BASH as root.
elif [[ "${1//-}" = [Cc]* ]] ; then
printf '\033]2; startarch command ARGS 📲  \007'
touch /data/data/com.termux/files/home/arch/root/.chushlogin
set +Eeuo pipefail
exec proot --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch -b /data/data/com.termux/files/home/arch/tmp:/dev/shm -b /data/data/com.termux/files/home/arch/var/binds/fbindprocstat:/proc/stat -b /proc/self/fd/1:/dev/stdout -b /proc/self/fd/2:/dev/stderr -b "$ANDROID_DATA" -b /dev/ -b "$EXTERNAL_STORAGE" -b "$HOME" -b /proc/ -b /storage/ -b /sys/ -w "$PWD" /usr/bin/env -i HOME=/root TERM=xterm-256color  /bin/bash -lc "$ar2ar" ||:
set -Eeuo pipefail
printf '\033]2; startarch command ARGS 📲  \007'
rm -f /data/data/com.termux/files/home/arch/root/.chushlogin
# [login user|login user [options]] Login as user [plus options].  Use `addauser user` first to create this user and user's home directory.
elif [[ "${1//-}" = [Ll]* ]] || [[ "${1//-}" = [Uu]* ]] ; then
printf '\033]2; startarch login user [options] 📲  \007'
set +Eeuo pipefail
exec proot --kill-on-exit -0 -r /data/data/com.termux/files/home/arch -b /data/data/com.termux/files/home/arch/tmp:/dev/shm -b /data/data/com.termux/files/home/arch/var/binds/fbindprocstat:/proc/stat -b /proc/self/fd/1:/dev/stdout -b /proc/self/fd/2:/dev/stderr -b "$ANDROID_DATA" -b /dev/ -b "$EXTERNAL_STORAGE" -b "$HOME" -b /proc/ -b /storage/ -b /sys/ -w "$PWD" /usr/bin/env -i HOME=/root TERM=xterm-256color  /bin/su - "$ar2ar" ||:
set -Eeuo pipefail
printf '\033]2; startarch login user [options] 📲  \007'
# [raw ARGS] Construct the `startarch` proot statement.  For example `startarch r su` will exec su in Arch Linux.  See PROOTSTMNT for more options; share your thoughts at https://github.com/sdrausty/TermuxArch/issues and https://github.com/sdrausty/TermuxArch/pulls.
elif [[ "${1//-}" = [Rr]* ]] ; then
printf '\033]2; startarch raw ARGS 📲  \007'
set +Eeuo pipefail
exec proot --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch -b /data/data/com.termux/files/home/arch/tmp:/dev/shm -b /data/data/com.termux/files/home/arch/var/binds/fbindprocstat:/proc/stat -b /proc/self/fd/1:/dev/stdout -b /proc/self/fd/2:/dev/stderr -b "$ANDROID_DATA" -b /dev/ -b "$EXTERNAL_STORAGE" -b "$HOME" -b /proc/ -b /storage/ -b /sys/ -w "$PWD" /usr/bin/env -i HOME=/root TERM=xterm-256color  /bin/"$ar2ar" ||:
set -Eeuo pipefail
printf '\033]2; startarch raw ARGS 📲  \007'
# [su user command] Login as user and execute command.  Use `addauser user` first to create this user and user's home directory.
elif [[ "${1//-}" = [Ss]* ]] ; then
printf '\033]2; startarch su user command 📲  \007'
if [[ "$2" = root ]];then
touch /data/data/com.termux/files/home/arch/root/.chushlogin
else
touch /data/data/com.termux/files/home/arch/home/"$2"/.chushlogin
fi
set +Eeuo pipefail
exec proot --kill-on-exit -0 -r /data/data/com.termux/files/home/arch -b /data/data/com.termux/files/home/arch/tmp:/dev/shm -b /data/data/com.termux/files/home/arch/var/binds/fbindprocstat:/proc/stat -b /proc/self/fd/1:/dev/stdout -b /proc/self/fd/2:/dev/stderr -b "$ANDROID_DATA" -b /dev/ -b "$EXTERNAL_STORAGE" -b "$HOME" -b /proc/ -b /storage/ -b /sys/ -w "$PWD" /usr/bin/env -i HOME=/root TERM=xterm-256color  /bin/su - "$2" -c "$ar3ar" ||:
set -Eeuo pipefail
printf '\033]2; startarch su user command 📲  \007'
if [[ "$2" = root ]];then
rm -f /data/data/com.termux/files/home/arch/root/.chushlogin
else
rm -f /data/data/com.termux/files/home/arch/home/"$2"/.chushlogin
fi
else
_PRINTUSAGE_
fi
