#!/data/data/com.termux/files/usr/bin/bash
#
# Generate a list of installed pkgs in Termux.

# Generate a list of installed pkgs.
tmpfile="$(mktemp)"
pkg list-installed >"$tmpfile" 2>/dev/null
cut -d/ -f1 "$tmpfile" > termux-installed-pkgs
rm -f "$tmpfile"

# Delete the Listing... trash line.
sed -i -e 's/Listing...//' termux-installed-pkgs
sed -i -e '/^\s*$/d' termux-installed-pkgs

# Calculate the number of installed pkgs.
n_pkgs="$(wc -l termux-installed-pkgs | cut -d' ' -f1)"

# Print the number of installed pkgs.
printf '%s\n' "==> You have installed $n_pkgs packages"

rm -f ./termux-installed-pkgs
