#!/usr/bin/env bash
#
# TERmuxTHeme.

if [[ "$1" == --material-default ]]; then
  cp "${HOME}/progetti/themes/termux/material-default" \
     "${HOME}/.termux/colors.properties"
  termux-reload-settings
elif [[ "$1" == --material-palenight ]]; then
  cp "${HOME}/progetti/themes/termux/material-palenight" \
     "${HOME}/.termux/colors.properties"
  termux-reload-settings
elif [[ "$1" == --material-darker ]]; then
  cp "${HOME}/progetti/themes/termux/material-darker" \
     "${HOME}/.termux/colors.properties"
  termux-reload-settings
elif [[ "$1" == --material-ocean ]]; then
  cp "${HOME}/progetti/themes/termux/material-ocean" \
     "${HOME}/.termux/colors.properties"
  termux-reload-settings
elif [[ "$1" == --material-lighter ]]; then
  cp "${HOME}/progetti/themes/termux/material-lighter" \
     "${HOME}/.termux/colors.properties"
  termux-reload-settings
elif [[ "$1" == --gruvbox-dark ]]; then
  cp "${HOME}/progetti/themes/termux/gruvbox-dark" \
     "${HOME}/.termux/colors.properties"
  termux-reload-settings
elif [[ "$1" == --gruvbox-light ]]; then
  cp "${HOME}/progetti/themes/termux/gruvbox-light" \
     "${HOME}/.termux/colors.properties"
  termux-reload-settings
elif [[ "$1" == --dark+ ]]; then
  cp "${HOME}/progetti/themes/termux/dark+" \
     "${HOME}/.termux/colors.properties"
  termux-reload-settings
elif [[ -z "$1" || "$1" == --auto || "$1" == -a ]]; then
  if [[ "$(<"${HOME}/.current-theme")" == 'M Default' ]]; then
    cp "${HOME}/progetti/themes/termux/material-default" \
       "${HOME}/.termux/colors.properties"
    termux-reload-settings
  elif [[ "$(<"${HOME}/.current-theme")" == 'M Palenight' ]]; then
    cp "${HOME}/progetti/themes/termux/material-palenight" \
       "${HOME}/.termux/colors.properties"
    termux-reload-settings
  elif [[ "$(<"${HOME}/.current-theme")" == 'M Darker' ]]; then
    cp "${HOME}/progetti/themes/termux/material-darker" \
       "${HOME}/.termux/colors.properties"
    termux-reload-settings
  elif [[ "$(<"${HOME}/.current-theme")" == 'M Ocean' ]]; then
    cp "${HOME}/progetti/themes/termux/material-ocean" \
       "${HOME}/.termux/colors.properties"
    termux-reload-settings
  elif [[ "$(<"${HOME}/.current-theme")" == 'M Lighter' ]]; then
    cp "${HOME}/progetti/themes/termux/material-lighter" \
       "${HOME}/.termux/colors.properties"
    termux-reload-settings
  elif [[ "$(<"${HOME}/.current-theme")" == 'D+' ]]; then
    cp "${HOME}/progetti/themes/termux/dark+" \
       "${HOME}/.termux/colors.properties"
    termux-reload-settings
  elif [[ "$(<"${HOME}/.current-theme")" == 'G Dark' ]]; then
    cp "${HOME}/progetti/themes/termux/gruvbox-dark" \
       "${HOME}/.termux/colors.properties"
    termux-reload-settings
  elif [[ "$(<"${HOME}/.current-theme")" == 'G Light' ]]; then
    cp "${HOME}/progetti/themes/termux/gruvbox-light" \
       "${HOME}/.termux/colors.properties"
    termux-reload-settings
  fi
fi
