#!/usr/bin/env bash
#
# A script that changes my terminal colorscheme.

# Change the terminal colors to source.
refresh_theme() {
  if [[ "$1" == --one-dark ]]; then
    sed -i -e 's/! Source .*/! Source one-dark colors\./' \
           -e 's_#include .*_#include "/home/matte/progetti/themes/xresources/one-dark.Xresources"_' \
           "${HOME}/.Xresources"

    # shellcheck disable=SC2016
    sed -i -e 's/# Source .*/# Source one-dark colors./' \
           -e 's_^\. .*_\. $HOME/progetti/themes/sh/one-dark.fish_' \
           "${HOME}/.config/fish/config.fish"

    sed -i -e 's/# Source .*/# Source one-dark colors\./' \
           -e 's_include .*_include "/home/matte/progetti/themes/zathura/one-dark.zathura"_' \
           "${HOME}/.config/zathura/zathurarc"

    sed -i -e 's_^  <name>Theme .*_  <name>Theme One Dark</name>_' \
           "${HOME}/.config/openbox/rc.xml"

    sed -i -e 's_^rofi.theme: .*_rofi.theme:             progetti/themes/rofi/one-dark.rasi_' \
           "${HOME}/.Xresources"

    sed -i -e "s/^colorscheme .*/colorscheme one-dark/" \
           "${HOME}/.config/nvim/init.vim"

    feh --bg-fill "${HOME}/progetti/wallpapers/one-dark.png"

    cp "${HOME}/progetti/themes/telegram/one-dark.tdesktop-palette" \
       "${HOME}/.cache/telegram-palette-gen/colors.tdesktop-palette"

    cp "${HOME}/progetti/wallpapers/one-dark.png" \
       "${HOME}/.cache/telegram-palette-gen/background.png"

    printf '%s\n' "OD" >"${HOME}/.current-theme"

  elif [[ "$1" == --one-light ]]; then
    sed -i -e 's/! Source .*/! Source one-light colors\./' \
           -e 's_#include .*_#include "/home/matte/progetti/themes/xresources/one-light.Xresources"_' \
           "${HOME}/.Xresources"

    # shellcheck disable=SC2016
    sed -i -e 's/# Source .*/# Source one-light colors./' \
           -e 's_^\. .*_\. $HOME/progetti/themes/sh/one-light.fish_' \
           "${HOME}/.config/fish/config.fish"

    sed -i -e 's/# Source .*/# Source one-light colors\./' \
           -e 's_include .*_include "/home/matte/progetti/themes/zathura/one-light.zathura"_' \
           "${HOME}/.config/zathura/zathurarc"

    sed -i -e 's_^  <name>Theme .*_  <name>Theme One Light</name>_' \
           "${HOME}/.config/openbox/rc.xml"

    sed -i -e 's_^rofi.theme: .*_rofi.theme:             progetti/themes/rofi/one-light.rasi_' \
           "${HOME}/.Xresources"

    sed -i -e "s/^colorscheme .*/colorscheme one-light/" \
           "${HOME}/.config/nvim/init.vim"

    feh --bg-fill "${HOME}/progetti/wallpapers/one-light.png"

    cp "${HOME}/progetti/themes/telegram/one-light.tdesktop-palette" \
       "${HOME}/.cache/telegram-palette-gen/colors.tdesktop-palette"

    cp "${HOME}/progetti/wallpapers/one-light.png" \
       "${HOME}/.cache/telegram-palette-gen/background.png"

    printf '%s\n' "OL" >"${HOME}/.current-theme"

  elif [[ "$1" == --material-default ]]; then
    sed -i -e 's/! Source .*/! Source material-default colors\./' \
           -e 's_#include .*_#include "/home/matte/progetti/themes/xresources/material-default.Xresources"_' \
           "${HOME}/.Xresources"

    # shellcheck disable=SC2016
    sed -i -e 's/# Source .*/# Source material-default colors./' \
           -e 's_^\. .*_\. $HOME/progetti/themes/sh/material-default.fish_' \
           "${HOME}/.config/fish/config.fish"

    sed -i -e 's/# Source .*/# Source material-default colors\./' \
           -e 's_include .*_include "/home/matte/progetti/themes/zathura/material-default.zathura"_' \
           "${HOME}/.config/zathura/zathurarc"

    sed -i -e 's_^  <name>Theme .*_  <name>Theme Material Default</name>_' \
           "${HOME}/.config/openbox/rc.xml"

    sed -i -e 's_^rofi.theme: .*_rofi.theme:             progetti/themes/rofi/material-default.rasi_' \
           "${HOME}/.Xresources"

    sed -i -e "s/^colorscheme .*/colorscheme material/" \
           -e "s/^let g:material_variant = .*/let g:material_variant = 'default'/" \
           "${HOME}/.config/nvim/init.vim"

    feh --bg-fill "${HOME}/progetti/wallpapers/material-default.png"

    cp "${HOME}/progetti/themes/telegram/material-default.tdesktop-palette" \
       "${HOME}/.cache/telegram-palette-gen/colors.tdesktop-palette"

    cp "${HOME}/progetti/wallpapers/material-default.png" \
       "${HOME}/.cache/telegram-palette-gen/background.png"

    printf '%s\n' "M Default" >"${HOME}/.current-theme"

  elif [[ "$1" == --material-palenight ]]; then
    sed -i -e 's/! Source .*/! Source material-palenight colors\./' \
           -e 's_#include .*_#include "/home/matte/progetti/themes/xresources/material-palenight.Xresources"_' \
           "${HOME}/.Xresources"

    # shellcheck disable=SC2016
    sed -i -e 's/# Source .*/# Source material-palenight colors./' \
           -e 's_^\. .*_\. $HOME/progetti/themes/sh/material-palenight.fish_' \
           "${HOME}/.config/fish/config.fish"

    sed -i -e 's/# Source .*/# Source material-palenight colors\./' \
           -e 's_include .*_include "/home/matte/progetti/themes/zathura/material-palenight.zathura"_' \
           "${HOME}/.config/zathura/zathurarc"

    sed -i -e 's_^  <name>Theme .*_  <name>Theme Material Palenight</name>_' \
           "${HOME}/.config/openbox/rc.xml"

    sed -i -e 's_^rofi.theme: .*_rofi.theme:             progetti/themes/rofi/material-palenight.rasi_' \
           "${HOME}/.Xresources"

    sed -i -e "s/^colorscheme .*/colorscheme material/" \
           -e "s/^let g:material_variant = .*/let g:material_variant = 'palenight'/" \
           "${HOME}/.config/nvim/init.vim"

    feh --bg-fill "${HOME}/progetti/wallpapers/material-palenight.png"

    cp "${HOME}/progetti/themes/telegram/material-palenight.tdesktop-palette" \
       "${HOME}/.cache/telegram-palette-gen/colors.tdesktop-palette"

    cp "${HOME}/progetti/wallpapers/material-palenight.png" \
       "${HOME}/.cache/telegram-palette-gen/background.png"

    printf '%s\n' "M Palenight" >"${HOME}/.current-theme"

  elif [[ "$1" == --material-darker ]]; then
    sed -i -e 's/! Source .*/! Source material-darker colors\./' \
           -e 's_#include .*_#include "/home/matte/progetti/themes/xresources/material-darker.Xresources"_' \
           "${HOME}/.Xresources"

    # shellcheck disable=SC2016
    sed -i -e 's/# Source .*/# Source material-darker colors./' \
           -e 's_^\. .*_\. $HOME/progetti/themes/sh/material-darker.fish_' \
           "${HOME}/.config/fish/config.fish"

    sed -i -e 's/# Source .*/# Source material-darker colors\./' \
           -e 's_include .*_include "/home/matte/progetti/themes/zathura/material-darker.zathura"_' \
           "${HOME}/.config/zathura/zathurarc"

    sed -i -e 's_^  <name>Theme .*_  <name>Theme Material Darker</name>_' \
           "${HOME}/.config/openbox/rc.xml"

    sed -i -e 's_^rofi.theme: .*_rofi.theme:             progetti/themes/rofi/material-darker.rasi_' \
           "${HOME}/.Xresources"

    sed -i -e "s/^colorscheme .*/colorscheme material/" \
           -e "s/^let g:material_variant = .*/let g:material_variant = 'darker'/" \
           "${HOME}/.config/nvim/init.vim"

    feh --bg-fill "${HOME}/progetti/wallpapers/material-darker.png"

    cp "${HOME}/progetti/themes/telegram/material-darker.tdesktop-palette" \
       "${HOME}/.cache/telegram-palette-gen/colors.tdesktop-palette"

    cp "${HOME}/progetti/wallpapers/material-darker.png" \
       "${HOME}/.cache/telegram-palette-gen/background.png"

    printf '%s\n' "M Darker" >"${HOME}/.current-theme"

  elif [[ "$1" == --material-ocean ]]; then
    sed -i -e 's/! Source .*/! Source material-ocean colors\./' \
           -e 's_#include .*_#include "/home/matte/progetti/themes/xresources/material-ocean.Xresources"_' \
           "${HOME}/.Xresources"

    # shellcheck disable=SC2016
    sed -i -e 's/# Source .*/# Source material-ocean colors./' \
           -e 's_^\. .*_\. $HOME/progetti/themes/sh/material-ocean.fish_' \
           "${HOME}/.config/fish/config.fish"

    sed -i -e 's/# Source .*/# Source material-ocean colors\./' \
           -e 's_include .*_include "/home/matte/progetti/themes/zathura/material-ocean.zathura"_' \
           "${HOME}/.config/zathura/zathurarc"

    sed -i -e 's_^  <name>Theme .*_  <name>Theme Material Ocean</name>_' \
           "${HOME}/.config/openbox/rc.xml"

    sed -i -e 's_^rofi.theme: .*_rofi.theme:             progetti/themes/rofi/material-ocean.rasi_' \
           "${HOME}/.Xresources"

    sed -i -e "s/^colorscheme .*/colorscheme material/" \
           -e "s/^let g:material_variant = .*/let g:material_variant = 'ocean'/" \
           "${HOME}/.config/nvim/init.vim"

    feh --bg-fill "${HOME}/progetti/wallpapers/material-ocean.png"

    cp "${HOME}/progetti/themes/telegram/material-ocean.tdesktop-palette" \
       "${HOME}/.cache/telegram-palette-gen/colors.tdesktop-palette"

    cp "${HOME}/progetti/wallpapers/material-ocean.png" \
       "${HOME}/.cache/telegram-palette-gen/background.png"

    printf '%s\n' "M Ocean" >"${HOME}/.current-theme"

  elif [[ "$1" == --gruvbox-dark ]]; then
    sed -i -e 's/! Source .*/! Source gruvbox-dark colors\./' \
           -e 's_#include .*_#include "/home/matte/progetti/themes/xresources/gruvbox-dark.Xresources"_' \
           "${HOME}/.Xresources"

    # shellcheck disable=SC2016
    sed -i -e 's/# Source .*/# Source gruvbox-dark colors./' \
           -e 's_^\. .*_\. $HOME/progetti/themes/sh/gruvbox-dark.fish_' \
           "${HOME}/.config/fish/config.fish"

    sed -i -e 's/# Source .*/# Source gruvbox-dark colors\./' \
           -e 's_include .*_include "/home/matte/progetti/themes/zathura/gruvbox-dark.zathura"_' \
           "${HOME}/.config/zathura/zathurarc"

    sed -i -e 's_^  <name>Theme .*_  <name>Theme Gruvbox Dark</name>_' \
           "${HOME}/.config/openbox/rc.xml"

    sed -i -e 's_^rofi.theme: .*_rofi.theme:             progetti/themes/rofi/gruvbox-dark.rasi_' \
           "${HOME}/.Xresources"

    sed -i -e "s/^colorscheme .*/colorscheme gruvbox/" \
           -e "s/^let g:gruvbox_variant = .*/let g:gruvbox_variant = 'dark'/" \
           "${HOME}/.config/nvim/init.vim"

    feh --bg-fill "${HOME}/progetti/wallpapers/gruvbox-dark.png"

    cp "${HOME}/progetti/themes/telegram/gruvbox-dark.tdesktop-palette" \
       "${HOME}/.cache/telegram-palette-gen/colors.tdesktop-palette"

    cp "${HOME}/progetti/wallpapers/gruvbox-dark.png" \
       "${HOME}/.cache/telegram-palette-gen/background.png"

    printf '%s\n' "GD" >"${HOME}/.current-theme"

  elif [[ "$1" == --dark-plus ]]; then
    sed -i -e 's/! Source .*/! Source dark-plus colors\./' \
           -e 's_#include .*_#include "/home/matte/progetti/themes/xresources/dark-plus.Xresources"_' \
           "${HOME}/.Xresources"

    # shellcheck disable=SC2016
    sed -i -e 's/# Source .*/# Source dark-plus colors./' \
           -e 's_^\. .*_\. $HOME/progetti/themes/sh/dark-plus.fish_' \
           "${HOME}/.config/fish/config.fish"

    sed -i -e 's/# Source .*/# Source dark-plus colors\./' \
           -e 's_include .*_include "/home/matte/progetti/themes/zathura/dark-plus.zathura"_' \
           "${HOME}/.config/zathura/zathurarc"

    sed -i -e 's_^  <name>Theme .*_  <name>Theme Dark Plus</name>_' \
           "${HOME}/.config/openbox/rc.xml"

    sed -i -e 's_^rofi.theme: .*_rofi.theme:             progetti/themes/rofi/dark-plus.rasi_' \
           "${HOME}/.Xresources"

    sed -i -e "s/^colorscheme .*/colorscheme dark-plus/" \
           "${HOME}/.config/nvim/init.vim"

    feh --bg-fill "${HOME}/progetti/wallpapers/dark-plus.png"

    cp "${HOME}/progetti/themes/telegram/dark-plus.tdesktop-palette" \
       "${HOME}/.cache/telegram-palette-gen/colors.tdesktop-palette"

    cp "${HOME}/progetti/wallpapers/dark-plus.png" \
       "${HOME}/.cache/telegram-palette-gen/background.png"

    printf '%s\n' "DP" >"${HOME}/.current-theme"

  fi
}

# Reload .Xresources.
reload_xres() {
  xrdb "${HOME}/.Xresources"
}

# Apply colors to dunst.
refresh_dunst() {
  killall -9 dunst
  dunst \
    -lb "$color0" \
    -nb "$color0" \
    -cb "$color1" \
    -lf "$color7" \
    -nf "$color7" \
    -cf "$color0" \
    -lfr "$color0" \
    -nfr "$color0" \
    -cfr "$color1" &
}

# Apply colors to tint2.
refresh_tint2() {
  sed -i -e "s/background_color = .*/background_color = ${color0} 100/" \
         -e "s/background_color_hover = .*/background_color_hover = ${color13} 100/" \
         -e "s/task_active_font_color = .*/task_active_font_color = ${color2} 100/" \
         -e "s/task_font_color = .*/task_font_color = ${color8} 100/" \
         "${HOME}/.config/tint2/tint2rc"
}

# Change some 'hardcoded' colors in the i3 config file.
refresh_i3() {
  #shellcheck disable=SC2016
  if [[ "$option" == --one-dark ]]; then
    sed -i -e 's/set               $dark .*/set               $dark #21252b/' \
           "${HOME}/.config/i3/config"
  elif [[ "$option" == --one-light ]]; then
    sed -i -e 's/set               $dark .*/set               $dark #eaeaeb/' \
           "${HOME}/.config/i3/config"
  elif [[ "$option" == --material-default ]]; then
    sed -i -e 's/set               $dark .*/set               $dark #192227/' \
           "${HOME}/.config/i3/config"
  elif [[ "$option" == --material-palenight ]]; then
    sed -i -e 's/set               $dark .*/set               $dark #1b1e2b/' \
           "${HOME}/.config/i3/config"
  elif [[ "$option" == --material-darker ]]; then
    sed -i -e 's/set               $dark .*/set               $dark #1a1a1a/' \
           "${HOME}/.config/i3/config"
  elif [[ "$option" == --material-ocean ]]; then
    sed -i -e 's/set               $dark .*/set               $dark #090b10/' \
           "${HOME}/.config/i3/config"
  elif [[ "$option" == --gruvbox-dark ]]; then
    sed -i -e 's/set               $dark .*/set               $dark #252526/' \
           "${HOME}/.config/i3/config"
  elif [[ "$option" == --dark-plus ]]; then
    sed -i -e 's/set               $dark .*/set               $dark #252526/' \
           "${HOME}/.config/i3/config"
  fi
}

# Change some color values for pqiv in rifle's rifle.conf config file.
refresh_rifle() {
  sed -i -e "s/--box-colors='#.*':'#.*'/--box-colors='${color7}':'${color0}'/" \
         "${HOME}/.config/ranger/rifle.conf"
}

# Change the alacritty colorscheme.
refresh_alacritty() {
  sed -i -e "s/background: '.*/background: '0x${color0:1:6}'/" \
         -e "s/foreground: '.*/foreground: '0x${color7:1:6}'/" \
         -e "s/text:   '.*/text:   '0x${color0:1:6}'/" \
         -e "s/cursor: '.*/cursor: '0x${color7:1:6}'/" \
         -e "s/black:   '.*/black:   '0x${color0:1:6}'/" \
         -e "s/red:     '.*/red:     '0x${color1:1:6}'/" \
         -e "s/green:   '.*/green:   '0x${color2:1:6}'/" \
         -e "s/yellow:  '.*/yellow:  '0x${color3:1:6}'/" \
         -e "s/blue:    '.*/blue:    '0x${color4:1:6}'/" \
         -e "s/magenta: '.*/magenta: '0x${color5:1:6}'/" \
         -e "s/cyan:    '.*/cyan:    '0x${color6:1:6}'/" \
         -e "s/white:   '.*/white:   '0x${color7:1:6}'/" \
         -e "s/black:    '.*/black:    '0x${color8:1:6}'/" \
         -e "s/red:      '.*/red:      '0x${color9:1:6}'/" \
         -e "s/green:    '.*/green:    '0x${color10:1:6}'/" \
         -e "s/yellow:   '.*/yellow:   '0x${color11:1:6}'/" \
         -e "s/blue:     '.*/blue:     '0x${color12:1:6}'/" \
         -e "s/magenta:  '.*/magenta:  '0x${color13:1:6}'/" \
         -e "s/cyan:     '.*/cyan:     '0x${color14:1:6}'/" \
         -e "s/white:    '.*/white:    '0x${color15:1:6}'/" \
         "${HOME}/.config/alacritty/alacritty.yml"
}

# Reload OpenBox.
reload_openbox() {
  openbox --restart
}

# Restart polybar.
restart_polybar() {
  if pgrep -x polybar; then
    killall -q polybar
    polybar bar &
  fi
}

# Refresh all the active terminals.
refresh_terminals() {
  for pid in $(pidof xst); do
    kill -s USR1 "$pid"
  done
}

main() {
  refresh_theme "$option"
  reload_xres

  if [[ "$option" == --one-dark ]]; then
    . "${HOME}/progetti/themes/sh/one-dark.sh"
  elif [[ "$option" == --one-light ]]; then
    . "${HOME}/progetti/themes/sh/one-light.sh"
  elif [[ "$option" == --material-default ]]; then
    . "${HOME}/progetti/themes/sh/material-default.sh"
  elif [[ "$option" == --material-palenight ]]; then
    . "${HOME}/progetti/themes/sh/material-palenight.sh"
  elif [[ "$option" == --material-darker ]]; then
    . "${HOME}/progetti/themes/sh/material-darker.sh"
  elif [[ "$option" == --material-ocean ]]; then
    . "${HOME}/progetti/themes/sh/material-ocean.sh"
  elif [[ "$option" == --gruvbox-dark ]]; then
    . "${HOME}/progetti/themes/sh/gruvbox-dark.sh"
  elif [[ "$option" == --dark-plus ]]; then
    . "${HOME}/progetti/themes/sh/dark-plus.sh"
  fi

  refresh_dunst
  refresh_tint2
  refresh_i3
  refresh_rifle
  refresh_alacritty
  reload_openbox
  restart_polybar
  refresh_terminals
}

option="$1"
main
