#!/usr/bin/env bash
#
# A script that changes my terminal colorscheme.

# Change the terminal colors to source.
refresh_theme() {
  sed -i -e 's/! Source .*/! Source one-dark colors\./' \
         -e 's_#include .*_#include "/home/matte/progetti/themes/xresources/one-dark.Xresources"_' \
         "${HOME}/.Xresources"

  # shellcheck disable=SC2016
  sed -i -e 's/# Source .*/# Source one-dark colors./' \
         -e 's_^\. .*_\. $HOME/progetti/themes/sh/one-dark.fish_' \
         "${HOME}/.config/fish/config.fish"

  sed -i -e 's/# Source .*/# Source one-dark colors\./' \
         -e 's_include .*_include "/home/matte/progetti/themes/zathura/one-dark.zathura"_' \
         "${HOME}/.config/zathura/zathurarc"

  sed -i -e 's_^  <name>Theme .*_  <name>Theme One Dark</name>_' \
         "${HOME}/.config/openbox/rc.xml"

  sed -i -e 's_^rofi.theme: .*_rofi.theme:             progetti/themes/rofi/one-dark.rasi_' \
         "${HOME}/.Xresources"

  sed -i -e "s/^colorscheme .*/colorscheme one-dark/" \
         "${HOME}/.config/nvim/init.vim"

  feh --bg-fill "${HOME}/progetti/wallpapers/one-dark.png"

  cp "${HOME}/progetti/themes/telegram/one-dark.tdesktop-palette" \
     "${HOME}/.cache/telegram-palette-gen/colors.tdesktop-palette"

  cp "${HOME}/progetti/wallpapers/one-dark.png" \
     "${HOME}/.cache/telegram-palette-gen/background.png"
}

# Reload .Xresources.
reload_xres() {
  xrdb "${HOME}/.Xresources"
}

# Apply colors to dunst.
refresh_dunst() {
  killall -9 dunst
  dunst \
    -lb "$color0" \
    -nb "$color0" \
    -cb "$color1" \
    -lf "$color7" \
    -nf "$color7" \
    -cf "$color0" \
    -lfr "$color0" \
    -nfr "$color0" \
    -cfr "$color1" &
}

# Change some color values for pqiv in rifle's rifle.conf config file.
refresh_rifle() {
  sed -i -e "s/--box-colors='#.*':'#.*'/--box-colors='${color7}':'${color0}'/" \
         "${HOME}/.config/ranger/rifle.conf"
}

# Change the alacritty colorscheme.
refresh_alacritty() {
  sed -i -e "s/background: '.*/background: '0x${color0:1:6}'/" \
         -e "s/foreground: '.*/foreground: '0x${color7:1:6}'/" \
         -e "s/text:   '.*/text:   '0x${color0:1:6}'/" \
         -e "s/cursor: '.*/cursor: '0x${color7:1:6}'/" \
         -e "s/black:   '.*/black:   '0x${color0:1:6}'/" \
         -e "s/red:     '.*/red:     '0x${color1:1:6}'/" \
         -e "s/green:   '.*/green:   '0x${color2:1:6}'/" \
         -e "s/yellow:  '.*/yellow:  '0x${color3:1:6}'/" \
         -e "s/blue:    '.*/blue:    '0x${color4:1:6}'/" \
         -e "s/magenta: '.*/magenta: '0x${color5:1:6}'/" \
         -e "s/cyan:    '.*/cyan:    '0x${color6:1:6}'/" \
         -e "s/white:   '.*/white:   '0x${color7:1:6}'/" \
         -e "s/black:    '.*/black:    '0x${color8:1:6}'/" \
         -e "s/red:      '.*/red:      '0x${color9:1:6}'/" \
         -e "s/green:    '.*/green:    '0x${color10:1:6}'/" \
         -e "s/yellow:   '.*/yellow:   '0x${color11:1:6}'/" \
         -e "s/blue:     '.*/blue:     '0x${color12:1:6}'/" \
         -e "s/magenta:  '.*/magenta:  '0x${color13:1:6}'/" \
         -e "s/cyan:     '.*/cyan:     '0x${color14:1:6}'/" \
         -e "s/white:    '.*/white:    '0x${color15:1:6}'/" \
         "${HOME}/.config/alacritty/alacritty.yml"
}

# Reload OpenBox.
reload_openbox() {
  openbox --restart
}

# Restart polybar.
restart_polybar() {
  if pgrep -x polybar; then
    killall -q polybar
    polybar bar &
  fi
}

# Refresh all the active terminals.
refresh_terminals() {
  for pid in $(pidof xst); do
    kill -s USR1 "$pid"
  done
}

main() {
  refresh_theme
  reload_xres

  . "${HOME}/progetti/themes/sh/one-dark.sh"

  refresh_dunst
  refresh_rifle
  refresh_alacritty
  reload_openbox
  restart_polybar
  refresh_terminals
}

main
