#!/usr/bin/env bash
#
# A minimal tmux status line that uses FontAwesome icons.
# It works only when in full screen (see the last if block).
# This is a modified version of the bar script by Dylan Araps.

# Display the screen brightness.
lum() {
  abr="$(</sys/class/backlight/intel_backlight/brightness)"
  mbr="$(( "$(</sys/class/backlight/intel_backlight/max_brightness)" / 100 ))"
  lum="\\uf0eb $((abr / mbr - 1))%"
}

# Display the ALSA volume value.
avol() {
  nperc="$(amixer sget Master \
    | tail -n1 \
    | cut -d' ' -f6 \
    | cut -d[ -f2 \
    | cut -d] -f1)"

  vsta="$(amixer sget Master \
    | tail -n1 \
    | cut -d' ' -f8 \
    | cut -d[ -f2 \
    | cut -d] -f1)"

  case "$nperc" in
    [0-9])  vol="\\uf026 ${nperc}%" ;;
    [1-4]?) vol="\\uf026 ${nperc}%" ;;
    [5-8]?) vol="\\uf027 ${nperc}%" ;;
    *)      vol="\\uf028 ${nperc}%" ;;
  esac

  if [[ "$vsta" == off ]]; then
    if [[ "$vol" =~ \ [0-9]%$ ]]; then
      vol="$(printf '%b' "$vol" | sed -e 's/[0-9]\+%/\.%/')"
    elif [[ "$vol" =~ \ [0-9][0-9]%$ ]]; then
      vol="$(printf '%b' "$vol" | sed -e 's/[0-9]\+%/\.\.%/')"
    elif [[ "$vol" =~ \ [0-9][0-9][0-9]%$ ]]; then
      vol="$(printf '%b' "$vol" | sed -e 's/[0-9]\+%/\.\.\.%/')"
    fi
  fi
}

# Display the PulseAudio volume value.
pvol() {
  nperc="$(pactl list sinks \
    | grep '^[[:space:]]Volume:' \
    | head -n"$((SINK + 1))" \
    | tail -n1 \
    | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')"

  vsta="$(amixer sget Master \
    | tail -n1 \
    | cut -d' ' -f8 \
    | cut -d[ -f2 \
    | cut -d] -f1)"

  case "$nperc" in
    [0-9])  vol="\\uf026 ${nperc}%" ;;
    [1-4]?) vol="\\uf026 ${nperc}%" ;;
    [5-8]?) vol="\\uf027 ${nperc}%" ;;
    *)      vol="\\uf028 ${nperc}%" ;;
  esac

  if [[ "$vsta" == off ]]; then
    if [[ "$vol" =~ \ [0-9]%$ ]]; then
      vol="$(printf '%b' "$vol" | sed -e 's/[0-9]\+%/\.%/')"
    elif [[ "$vol" =~ \ [0-9][0-9]%$ ]]; then
      vol="$(printf '%b' "$vol" | sed -e 's/[0-9]\+%/\.\.%/')"
    elif [[ "$vol" =~ \ [0-9][0-9][0-9]%$ ]]; then
      vol="$(printf '%b' "$vol" | sed -e 's/[0-9]\+%/\.\.\.%/')"
    fi
  fi
}

# Display the SSID name.
ssid() {
  if [[ -z "$(iwgetid -r)" ]]; then
    ssid="\\uf1eb  -"
  elif [[ "$(iwgetid -r)" ]]; then
    ssid="\\uf1eb  $(iwgetid -r)"
  fi
}

# Display the battery percentage.
bat() {
  sta="$(</sys/class/power_supply/BAT0/status)"
  cap="$(</sys/class/power_supply/BAT0/capacity)"

  if [[ "$sta" == Charging ]]; then
    case "$cap" in
      [0-9])  bat="\\uf244  \\uf0e7 ${cap}%" ;;
      [1-3]?) bat="\\uf243  \\uf0e7 ${cap}%" ;;
      [4-6]?) bat="\\uf242  \\uf0e7 ${cap}%" ;;
      [7-9]?) bat="\\uf241  \\uf0e7 ${cap}%" ;;
      *)      bat="\\uf240  \\uf0e7 100%" ;;
    esac
  else
    case "$cap" in
      [0-9])  bat="\\uf244   ${cap}%" ;;
      [1-3]?) bat="\\uf243   ${cap}%" ;;
      [4-6]?) bat="\\uf242   ${cap}%" ;;
      [7-9]?) bat="\\uf241   ${cap}%" ;;
      *)      bat="\\uf240   100%" ;;
    esac
  fi
}

# Display the date.
data() {
  data="\\uf274  $(printf "%(%a %d %b)T" "-1")"
}

# Display the time.
ore() {
  ore="\\uf017  $(printf "%(%H:%M)T" "-1")"
}

# If tmux is on fullscreen, display the bar.
if (("${1:-165}" >= 164 && "${2:-35}" >= 34)); then
  lum
  pvol
  ssid
  bat
  data
  ore
  [[ "$sta" == Discharging ]] && \
    printf '%b\n' "$ssid   $bat   $vol   $lum   $data   $ore"
  [[ "$sta" == Charging ]] && \
    printf '%b\n' "$ssid   $bat   $vol   $lum   $data   $ore"
fi
