#!/usr/bin/env bash
#
# Turing machine in bash because I am a masochist.

# Convert "$tape" to an array.
input_to_tape_array() {
  for ((c=0; c<"${#1}"; c++)); do
    declare -ga tape[$c]="${1:$c:1}"
  done
}

# Convert the "$tape" array to a better looking output.
tape_array_to_output() {
  tape_len="${#tape[@]}"

  for i in "${!tape[@]}"; do
    [[ "${tape[$i]}" == '-' ]] && unset -v tape["$i"]
  done

  for ((c=0; c<"$tape_len"; c++)); do
    output+="${tape[$c]}"
  done

  printf '%s\n' "$output"
}

# Parse arguments.
if [[ "$1" == --mdt || "$1" == -m ]]; then
  mdt="$2"
  input_to_tape_array "$4"
elif [[ "$1" == --tape || "$1" == -t ]]; then
  mdt="$4"
  input_to_tape_array "$2"
fi

mdt_len="$(wc -l "$mdt" | awk '{print $1}')"
actual_state=0
actual_char=0
continue=true

while [[ "$continue" == true ]]; do
  continue=false

  for ((c=1; c<="$mdt_len"; c++)); do
    # shellcheck disable=SC2155
    declare -a current_instruction="$(printf '%s\n' "$(<"$mdt")" \
                                     | head -n"$c" \
                                     | tail -n1 \
                                     | sed -e "s/,/ /g" \
                                           -e "s/>/'>'/g" \
                                           -e "s/</'<'/g")"

    # If the initial state is the actual state.
    if [[ "${current_instruction[0]}" -eq "$actual_state" ]]; then
      continue=true

      # If the read charachter is equal to the actual character in the "$tape".
      if [[ "${current_instruction[1]}" == "${tape[$actual_char]}" ]]; then
        actual_state="${current_instruction[2]}"
        declare -a tape[$actual_char]="${current_instruction[3]}"

        if [[ "${current_instruction[4]}" == '>' ]]; then
          actual_char="$((actual_char + 1))"
          [[ "${#tape[@]}" -lt "$((actual_char + 1))" ]] && tape+=(-)
        elif [[ "${current_instruction[4]}" == '<' ]]; then
          actual_char="$((actual_char - 1))"
          [[ "$actual_char" -lt 0 ]] && tape=(- "${tape[@]}") && actual_char=0
        elif [[ "${current_instruction[4]}" == '-' ]]; then
          continue=false
          break
        fi
      fi
    fi
  done
done

tape_array_to_output
