#!/usr/bin/env bash

check-requirements-wrapper grep awk pacmd

muted="$(pacmd list-sinks | grep -A 15 '* index' | awk '/muted/ { print $2 }')"
if [[ "${muted}" == yes ]]; then
    printf '%s\n' "Muted"
else
    printf '%s\n' "Non muted"
fi

