#!/usr/bin/env bash

slap deps grep awk pacmd || exit 1

muted="$(pacmd list-sinks | grep -A 15 '* index' | awk '/muted/ { print $2 }')"
if [[ "${muted}" == yes ]]; then
    printf '%s\n' "Muted"
else
    printf '%s\n' "Non muted"
fi

