#!/usr/bin/env bash
#
# Hook script executed by pywal (works with light version).

# Set the value of color17 to $color0_darker_20 for all the active terminals.
add_colors_variants() {
  for term in /dev/pts/[0-9]*; do
    if [[ -w "$term" ]]; then
      printf '%b' "\\e]4;17;rgb:${color0_darker_20:1:2}/${color0_darker_20:3:2}/${color0_darker_20:5:2}\\e\\" > "$term"
    fi
  done
}

# Change the value for some highlight groups.
restyle_fish() {
  sed -i -e "s/fish_color_autosuggestion    .*/fish_color_autosuggestion    ${color0_darker_20:1:6}/" \
         -e "s/fish_pager_color_progress    .*/fish_pager_color_progress    ${color0:1:6}/" \
         -e "s/fish_pager_color_description .*/fish_pager_color_description ${color8:1:6}/" \
         "${HOME}/.config/fish/config.fish"
}

# Apply colors to dunst.
restyle_dunst() {
  killall -9 dunst
  dunst \
    -lb "$color0" \
    -nb "$color0" \
    -cb "$color1" \
    -lf "$color7" \
    -nf "$color7" \
    -cf "$color0" \
    -lfr "$color0" \
    -nfr "$color0" \
    -cfr "$color1" &
}

# Generate a theme for zathura.
restyle_zathura() {
  cat <<EOF >"${HOME}/.cache/wal/colors-zathura"
set default-bg              "$color0"
set default-fg              "$color7"
set highlight-color         "$color0_darker_20"
set highlight-active-color  "$color1"
set completion-bg           "$color0"
set completion-fg           "$color0_darker_20"
set completion-highlight-bg "$color0"
set completion-highlight-fg "$color1"
set statusbar-bg            "$color1"
set statusbar-fg            "$color0"
set inputbar-bg             "$color0"
set inputbar-fg             "$color7"
EOF
}

# Apply the colors to my OpenBox theme.
restyle_openbox() {
  sed -i -e "s/bg.color:       #.*/bg.color:       ${color0}/" \
         -e "s/text.color:     #.*/text.color:     ${color7}/" \
         -e "s/image.color: #.*/image.color: ${color7}/" \
         -e "s/menu.items.bg.color:          #.*/menu.items.bg.color:          ${color0}/" \
         -e "s/menu.items.text.color:        #.*/menu.items.text.color:        ${color0_darker_20}/" \
         -e "s/menu.items.active.bg.color:   #.*/menu.items.active.bg.color:   ${color0}/" \
         -e "s/menu.items.active.text.color: #.*/menu.items.active.text.color: ${color1}/" \
         -e "s/menu.border.color:            #.*/menu.border.color:            ${color0}/" \
         -e "s/menu.separator.color:         #.*/menu.separator.color:         ${color0}/" \
         "${HOME}/.themes/Samiero/openbox-3/themerc"
  openbox --reconfigure
}

# Make fzf more minimal.
restyle_fzf() {
  old_string_1="--color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255"
  new_string_1="--color fg:17,hl:1,fg+:1,bg+:0,hl+:7"
  sed -i -e "s/${old_string_1}/${new_string_1}/" \
         "${HOME}/.cache/wal/colors.sh"
  sed -i -e "s/${old_string_1}/${new_string_1}/" \
         "${HOME}/.cache/wal/colors.fish"

  old_string_2="--color info:7,prompt:2,spinner:1,pointer:232,marker:1"
  new_string_2="--color info:0,prompt:1,spinner:1,pointer:1,marker:1"
  sed -i -e "s/${old_string_2}/${new_string_2}/" \
         "${HOME}/.cache/wal/colors.sh"
  sed -i -e "s/${old_string_2}/${new_string_2}/" \
         "${HOME}/.cache/wal/colors.fish"
}

# Set radius to rofi and apply some modifications to the colors.
restyle_rofi() {
  sed -i -e "33i\\ \\ \\ \\ border-radius: 4;" \
         -e "s/^    active-foreground: @.*/    active-foreground: ${color0_darker_20};/" \
         -e "s/^    normal-foreground: @.*/    normal-foreground: ${color0_darker_20};/" \
         -e "s/^    urgent-foreground: @.*/    urgent-foreground: ${color0_darker_20};/" \
         -e "s/^    alternate-active-foreground: @.*/    alternate-active-foreground: ${color0_darker_20};/" \
         -e "s/^    alternate-normal-foreground: @.*/    alternate-normal-foreground: ${color0_darker_20};/" \
         -e "s/^    alternate-urgent-foreground: @.*/    alternate-urgent-foreground: ${color0_darker_20};/" \
         -e "s/^    selected-active-background: #.*/    selected-normal-background: @background;/" \
         -e "s/^    selected-active-foreground: @.*/    selected-normal-foreground: ${color1};/" \
         -e "s/^    selected-normal-background: #.*/    selected-normal-background: @background;/" \
         -e "s/^    selected-normal-foreground: @.*/    selected-normal-foreground: ${color1};/" \
         -e "s/^    selected-urgent-background: #.*/    selected-normal-background: @background;/" \
         -e "s/^    selected-urgent-foreground: @.*/    selected-normal-foreground: ${color1};/" \
         "${HOME}/.cache/wal/colors-rofi-dark.rasi"
}

# Change some color values for pqiv in rifle's rifle.conf config file.
restyle_rifle() {
  sed -i -e "s/--box-colors='#.*':'#.*'/--box-colors='${color7}':'${color0}'/" \
         "${HOME}/.config/ranger/rifle.conf"
}

# Change the alacritty colorscheme.
restyle_alacritty() {
  sed -i -e "s/background: '.*/background: '0x${color0:1:6}'/" \
         -e "s/foreground: '.*/foreground: '0x${color7:1:6}'/" \
         -e "s/text:   '.*/text:   '0x${color0:1:6}'/" \
         -e "s/cursor: '.*/cursor: '0x${color7:1:6}'/" \
         -e "s/black:   '.*/black:   '0x${color0:1:6}'/" \
         -e "s/red:     '.*/red:     '0x${color1:1:6}'/" \
         -e "s/green:   '.*/green:   '0x${color2:1:6}'/" \
         -e "s/yellow:  '.*/yellow:  '0x${color3:1:6}'/" \
         -e "s/blue:    '.*/blue:    '0x${color4:1:6}'/" \
         -e "s/magenta: '.*/magenta: '0x${color5:1:6}'/" \
         -e "s/cyan:    '.*/cyan:    '0x${color6:1:6}'/" \
         -e "s/white:   '.*/white:   '0x${color7:1:6}'/" \
         -e "s/black:    '.*/black:    '0x${color8:1:6}'/" \
         -e "s/red:      '.*/red:      '0x${color9:1:6}'/" \
         -e "s/green:    '.*/green:    '0x${color10:1:6}'/" \
         -e "s/yellow:   '.*/yellow:   '0x${color11:1:6}'/" \
         -e "s/blue:     '.*/blue:     '0x${color12:1:6}'/" \
         -e "s/magenta:  '.*/magenta:  '0x${color13:1:6}'/" \
         -e "s/cyan:     '.*/cyan:     '0x${color14:1:6}'/" \
         -e "s/white:    '.*/white:    '0x${color15:1:6}'/" \
         -e "s/black:     '.*/black:     '0x${color0_lighter_20:1:6}'/" \
         -e "s/red:       '.*/red:       '0x${color1_lighter_20:1:6}'/" \
         -e "s/green:     '.*/green:     '0x${color2_lighter_20:1:6}'/" \
         -e "s/yellow:    '.*/yellow:    '0x${color3_lighter_20:1:6}'/" \
         -e "s/blue:      '.*/blue:      '0x${color4_lighter_20:1:6}'/" \
         -e "s/magenta:   '.*/magenta:   '0x${color5_lighter_20:1:6}'/" \
         -e "s/cyan:      '.*/cyan:      '0x${color6_lighter_20:1:6}'/" \
         -e "s/white:     '.*/white:     '0x${color7_lighter_20:1:6}'/" \
         "${HOME}/.config/alacritty/alacritty.yml"
}

main() {
  printf '%s' "light" > "${HOME}/.cache/wal/mode"
  "${HOME}/progetti/extend-wal/extend-wal"
  # shellcheck source=/dev/null
  . "${HOME}/.cache/wal/colors.sh"
  add_colors_variants
  restyle_fish
  restyle_dunst
  restyle_zathura
  restyle_openbox
  restyle_fzf
  restyle_rofi
  restyle_rifle
  restyle_alacritty
  "${HOME}/progetti/wal-telegram/wal-telegram"
  "${HOME}/altri_progetti/wal-discord/wal-discord"
}

main
