#!/usr/bin/env bash
#
# Hook script executed by pywal (works with dark version).

# Set the value of color17 to $color0_lighter_150 for all the active terminals.
add_colors_variants() {
  for term in /dev/pts/[0-9]*; do
    if [[ -w "$term" ]]; then
      printf "\e]4;17;rgb:${color0_lighter_150:1:2}/${color0_lighter_150:3:2}/${color0_lighter_150:5:2}\e\\" > "$term"
    fi
  done
}

# Apply colors to dunst.
fix_dunst() {
  killall -9 dunst
  dunst \
    -lb "$color0" \
    -nb "$color0" \
    -cb "$color1" \
    -lf "$color7" \
    -nf "$color7" \
    -cf "$color0" \
    -lfr "$color0" \
    -nfr "$color0" \
    -cfr "$color1" &
}

# Generate a theme for zathura.
fix_zathura() {
  cat <<EOF >"${HOME}/.cache/wal/colors-zathura"
set default-bg              "$color0"
set default-fg              "$color7"
set highlight-color         "$color0_lighter_150"
set highlight-active-color  "$color1"
set completion-bg           "$color0"
set completion-fg           "$color0_lighter_150"
set completion-highlight-bg "$color0"
set completion-highlight-fg "$color1"
set statusbar-bg            "$color1"
set statusbar-fg            "$color0"
set inputbar-bg             "$color0"
set inputbar-fg             "$color7"
EOF
}

# Apply the colors to my OpenBox theme.
fix_openbox() {
  sed -i -e "s/bg.color:       #.*/bg.color:       ${color0}/" \
         -e "s/text.color:     #.*/text.color:     ${color7}/" \
         -e "s/image.color: #.*/image.color: ${color7}/" \
         "${HOME}/.themes/Samiero/openbox-3/themerc"
  openbox --reconfigure
}

# Fix transparency with fzf in terminal.
fix_fzf_transparency() {
  old_string="--color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255"
  new_string="--color fg:7,hl:1,fg+:232,bg+:1,hl+:255"
  sed -i -e "s/${old_string}/${new_string}/" \
         "${HOME}/.cache/wal/colors.sh"
}

# Set radius to rofi and apply some modifications to the colors.
fix_rofi() {
  sed -i -e "33i\ \ \ \ border-radius: 4;" \
         -e "s/^    normal-foreground: @.*/normal-foreground: ${color0_lighter_150};/" \
         -e "s/^    alternate-normal-foreground: @.*/alternate-normal-foreground: ${color0_lighter_150};/" \
         -e "s/^    selected-normal-background: #.*/selected-normal-background: @background;/" \
         -e "s/^    selected-normal-foreground: @.*/selected-normal-foreground: ${color1};/" \
         "${HOME}/.cache/wal/colors-rofi-dark.rasi"
}

# Change some color values for pqiv in rifle's rifle.conf config file.
fix_rifle() {
  sed -i -e "s/--box-colors='#.*':'#.*'/--box-colors='${color7}':'${color0}'/" \
         "${HOME}/.config/ranger/rifle.conf"
}

main() {
  printf '%s' "dark" > "${HOME}/.cache/wal/mode"
  "${HOME}/progetti/extend-wal/extend-wal"
  # shellcheck source=/dev/null
  . "${HOME}/.cache/wal/colors.sh"
  add_colors_variants
  fix_dunst
  fix_zathura
  fix_openbox
  fix_fzf_transparency
  fix_rofi
  fix_rifle
  "${HOME}/progetti/wal-telegram/wal-telegram"
  "${HOME}/altri_progetti/wal-discord/wal-discord"
}

main
