#!/usr/bin/env bash
#
# This is a slightly different version of the polybar-workspaces script.
# The main difference is the final output.
# Requires wmctrl.
# Uses FontAwesome icons.

# Number of workspaces - 1.
nwo="$(( "$(xprop -root _NET_NUMBER_OF_DESKTOPS \
           | sed 's/_NET_NUMBER_OF_DESKTOPS(CARDINAL) = //')" - 1 ))"

# Create an array from 0 to "$nwo".
nwoar=0
for ((i=1; i<="$nwo"; i++)); do
  nwoar+=" $i"
done

# Index of the current workspace.
# shellcheck disable=SC2063
cwo="$(wmctrl -d \
      | grep '*' \
      | cut -d' ' -f1)"

# Create the first the first element of the active workspaces array.
if [[ "$(wmctrl -l | head -n1 | tail -n1 | cut -d' ' -f3)" ]]; then
  awos+="$(wmctrl -l \
          | head -n1 \
          | tail -n1 \
          | cut -d' ' -f3)"
fi

# Numbers of line of "$(wmctrl -l)".
nli="$(wmctrl -l | wc -l)"

# Create an array from 2 to the number of lines of "$nli".
nliar=2
for ((i=2; i<="$nli"; i++)); do
  nliar+=" $i"
done

# Use the $nliar array to create another array containing a list of workspaces
# that contains some windows (active workspaces).
for line in $nliar; do
  [[ "$(wmctrl -l | head -n"$line" | tail -n1)" ]] && \
    awos+=" $(wmctrl -l \
             | head -n"$line" \
             | tail -n1 \
             | cut -d' ' -f3)"
done

# Create a temp dir to store some files that represents the active workspaces.
# With this trick i get rid of all the duplicates.
tmpdir="$(mktemp -d)"
for awo in $awos; do
  [[ "$(wmctr -l | wc -l)" -ne 1 ]] && \
    touch "${tmpdir}/${awo}" &>/dev/null
done

# Print the final output.
for workspace in $nwoar; do
  if [[ -f "${tmpdir}/${workspace}" ]]; then
    if [[ "$workspace" -eq "$cwo" ]]; then
      printf '%b\n' "\\e[1;31mCurrent:  $((workspace + 1))\\e[0m"
    else
      printf '%b\n' "\\e[0;32mActive:   $((workspace + 1))\\e[0m"
    fi
  else
    if [[ "$workspace" -eq "$cwo" ]]; then
      printf '%b\n' "\\[0;32mActive:   $((workspace + 1))\\e[0m"
    else
      printf '%b\n' "Inactive: $((workspace + 1))"
    fi
  fi
done

# Remove the temp dir.
rm -rf "$tmpdir"
