#!/usr/bin/env bash
#
# Triggers zen mode.

# shellcheck source=/dev/null
. "${HOME}/.cache/wal/colors.sh"

# Kill sources of distraction.
pkill telegram

notify-send "Zen mode activated" "Ora concentrati e porta a termine il tuo obbiettivo."
