#!/usr/bin/env bash
#
# Triggers zen mode.

# shellcheck source=/dev/null
. "${HOME}/.cache/wal/colors.sh"

# Kill sources of distraction.
killall -9 telegram-desktop \
           Discord &> /dev/null

clear
printf '%s\n' "Ora concentrati e porta a termine il tuo obbiettivo."
